version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo install
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php ;
      - php -r "unlink('composer-setup.php');" ;
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo pre_build npm
      - echo `pwd`
      - echo `ls -a`
      - cd frontend
      - npm install
      - npm run build

      - echo pre_build composer
      - cd ../backend
      - echo `pwd`
      - echo `ls -a`
      - composer install --no-progress --no-suggest

  build:
    commands:
      - echo build
      - cd ../
      - echo `pwd`
      - echo `ls -a`

  post_build:
    commands:
      - echo post_build
      - mv frontend/public/index.js backend/public/index.js
