version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo install
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php ;
      - php -r "unlink('composer-setup.php');" ;
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo pre_build npm
      - echo `pwd`
      - cd frontend
      - npm install
      - echo pre_build composer
      - echo `pwd`

  build:
    commands:
      - echo build
      - npm run build 

  post_build:
    commands:
      - echo post_build
      - mv frontend/public/index.js backend/public/index.js
